# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ashraful Islam
title: Software Engineer
email: ashrafulrafi@gmail.com
Mobile: (88) 01722293046
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: rafithe47
# github_username:  sproogen
twitter_username: rafithe47
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: rafithe47
# flickr_username: jekyll
instagram_username: rafithe47
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Rafi and I'm a result-oriented software engineering professional with 5+ years of experience which includes 4+ years of hands-on Web Development and 1+ year of project management. I have worked at a number of companies gaining teamwork and leadership skills as well.

  I am most skilled in: <mark>Developing Software</mark> and <mark>Eating Pizza</mark>

content:
  - title: Research Background # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - **Research Experience:** Working in a research-based organization for the last 3 years
      - **Research interests:** Data Science, ML, Software Engineering, AI, Bioinformatics, Cyber Security

  - title: Programming Background # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - IUT 4th National ICT Fest - 2012, NSU ACM ICPC Dhaka Site - 2011, SUST Inter-University Programming Contest – 2011, IUT Inter-University Programming Contest – 2011.
      - Solved over 400 problems from different online judges.
      - Worked as a voluntary **ACM instructor while doing undergrad** in my university


  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PIPILIKA - BANGLA SEARCH ENGINE
        link: www.pipilika.com
        link_text: Search Engine Pipilika 
        sub_title: Software Engineer
        caption: August 2017 - Present
        
        # quote: >
        #   Bangladesh's first ever search engine 

        description: | # this will include new lines to allow paragraphs
          - Developing, fixing, and deploying custom Crawler and Parser for a variety of search services using Java
          - Developing and Implementing REST API using Spring Boot and Java Servlet API
          - Designing and implementing dynamic schema Using Apache Solr to index the crawled and parsed data
          - Modifying existing software services written in Java to correct functional errors and improve overall performance
          - Using rancher to manage all the dockerized service containers efficiently
          - Implemented TIG(Telegraf, InfluxDB & Grafana) Stack to monitor the whole infrastructure

      - layout: left
        title: PIPILIKA - BANGLA SEARCH ENGINE
        link: www.pipilika.com
        link_text: Search Engine Pipilika 
        sub_title: Software Engineer
        caption: August 2017 - Present
        
        # quote: >
        #   Bangladesh's first ever search engine 

        description: | # this will include new lines to allow paragraphs
          - Developing, fixing, and deploying custom Crawler and Parser for a variety of search services using Java
          - Developing and Implementing REST API using Spring Boot and Java Servlet API
          - Designing and implementing dynamic schema Using Apache Solr to index the crawled and parsed data
          - Modifying existing software services written in Java to correct functional errors and improve overall performance
          - Using rancher to manage all the dockerized service containers efficiently
          - Implemented TIG(Telegraf, InfluxDB & Grafana) Stack to monitor the whole infrastructure


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
