# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ashraful Islam Rafi
title: Software Engineer
email: ashrafulrafi@gmail.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
linkedin_username: rafithe47
# github_username:  sproogen
twitter_username: rafithe47
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: rafithe47
# flickr_username: jekyll
instagram_username: rafithe47
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Rafi and I'm a result-oriented software engineering professional with 5+ years of experience which includes 4+ years of hands-on Web Development and 1+ year of project management. I have worked at a number of companies gaining teamwork and leadership skills as well.

  

  I am most skilled in: <mark>Developing Software</mark> and <mark>Eating Pizza</mark>





content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: LEADING UNIVERSITY
        link: www.lus.ac.bd
        # link_text: Leading University, Sylhet
        caption: CGPA - 3.30 out of 4.00 <br/>2009 - 2013 
        sub_title: B. Sc. Computer Science and Engineering
        quote: >
          Leading University or LU is a private university in Bangladesh. It was established in 2001 under the Private University Act 1992. The campus of LU is located in Ragib Nagar, Kamal Bazar, South Surma, Sylhet, Bangladesh.
        description: | # this will include new lines to allow paragraphs
          During my time at LU, I learned most of the key skills that have I have taken through my career such as programming, teamwork, and working to tight deadlines.  

          I spent a lot of my free time as a committee member of the **Leading University Computer Club** taking on roles such as *Public Relation Officer* and *Vice-President*.

          I also served voluntarily as a *Security Assurance* member of the **Bangladesh National Cadet Corps Club** in my university.


  - title: Research Background # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - **Research Experience:** Working in a research-based organization for the last 3 years
      - **Research interests:** Data Science, ML, Software Engineering, AI, Bioinformatics, Cyber Security



  - title: Programming Background # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - IUT 4th National ICT Fest - 2012, NSU ACM ICPC Dhaka Site - 2011, SUST Inter-University Programming Contest – 2011, IUT Inter-University Programming Contest – 2011.
      - Solved over 400 problems from different online judges.
      - Worked as a voluntary **ACM instructor while doing undergrad** in my university


  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: PIPILIKA - BANGLA SEARCH ENGINE
        link: www.pipilika.com
        # link_text: Search Engine Pipilika 
        sub_title: Software Engineer
        caption: August 2017 - Present
        
        # quote: >
        #   Bangladesh's first ever search engine 

        description: | # this will include new lines to allow paragraphs
          - Developing, fixing, and deploying custom Crawler and Parser for a variety of search services using Java
          - Developing and Implementing REST API using Spring Boot and Java Servlet API
          - Designing and implementing dynamic schema Using Apache Solr to index the crawled and parsed data
          - Modifying existing software services written in Java to correct functional errors and improve overall performance
          - Using rancher to manage all the dockerized service containers efficiently
          - Implemented TIG(Telegraf, InfluxDB & Grafana) Stack to monitor the whole infrastructure

      - layout: left
        title: SOUTHEAST UNIVERSITY
        link: https://seu.edu.bd
        # link_text: Southeast University, Bangladesh
        sub_title: Programmer
        caption: April 2015 - August 2017
        
        # quote: >
        #   Bangladesh's first ever search engine 

        description: | # this will include new lines to allow paragraphs
          - Modify, correct, and improve the overall performance of the University Management System(UMS) software
          - Developed “Online Admission System” using PHP, MySql, jQuery, Ajax, Bootstrap3
          - Coordinated and Monitored vendor company on developing HRMS Software as per the SRS
          - Developed SMS Module which automatically sends last semester's results to parents
          - Wrote & Modified complicated MySql Queries to enhance project performance
          - Establish, build, and manage relationships with corporate partners.

      - layout: left
        title: DURBAR SOFTWARE
        link: https://durbar.co
        # link_text: Durbar Software, Bangladesh
        sub_title: Senior Software Engineer
        caption: Novermber 2014 - April 2015
        
        # quote: >
        #   Bangladesh's first ever search engine 

        description: | # this will include new lines to allow paragraphs
          - Developed Annual "Local Health Bulletin - 2015" System for Govt. Bangladesh under Health Ministry
          - Developed "Photo Archiver System" for Govt. Bangladesh under the Ministry Of Health and Family Welfare using CI, Ajax, MySql, jQuery, JSON, etc.
          - Used Bootstrap Framework for cross-platform compatibility

      - layout: left
        title: IT LAB SOLUTIONS LTD.
        link: www.itlabsolutions.com
        # link_text: IT Lab Solutions Ltd.
        sub_title: Software Developer(While Doing Undergraduate)
        caption: February 2012 - January 2014
        
        # quote: >
        #   Bangladesh's first ever search engine 

        description: | # this will include new lines to allow paragraphs
          - Designed and Developed Customized Web-Based Software for different Businesses
          - Involved in Back End coding to manage dynamic pages using the CodeIgnitor framework
          - According to client requirements redesigned PHP Scripts, MySQL queries, HTML, CSS.

  - title: Technical Skills # Title for the section
    layout: text # Type of content section (list/text)
    content: |
      - **Languages:** Working in a research-based organization for the last 3 years
      - **Databases:** Data Science, ML, Software Engineering, AI, Bioinformatics, Cyber Security
      - **Frameworks/Libraries/Others:** Spring Boot, Java Servlet, Jsoup, Scrapy, Codeigniter, Ajax, jQuery, Bootstrap3, Docker, Maven, Wordpress, Git

  

  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #     - Rock climbing
  #     - Gaming
  #     - Knitting
  #     - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #     Look at this cool image  
  #     ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: false
references_title: Email - ashrafulrafi@gmail.com, Mobile - (88) 01722293046

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
